<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-07-28T14:23:02 EEST" name="Default suite" finished-at="2020-07-28T14:23:07 EEST" duration-ms="5177">
    <groups>
    </groups>
    <test started-at="2020-07-28T14:23:02 EEST" name="Default test" finished-at="2020-07-28T14:23:07 EEST" duration-ms="5177">
      <class name="GET_Request.Request_Data">
        <test-method is-config="true" signature="setup()[pri:0, instance:GET_Request.Request_Data@229d10bd]" started-at="2020-07-28T14:23:02 EEST" name="setup" finished-at="2020-07-28T14:23:03 EEST" duration-ms="1009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC01_GetWeatherDetailsForValidCity()[pri:0, instance:GET_Request.Request_Data@229d10bd]" started-at="2020-07-28T14:23:03 EEST" name="TC01_GetWeatherDetailsForValidCity" finished-at="2020-07-28T14:23:06 EEST" duration-ms="3217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_GetWeatherDetailsForValidCity -->
        <test-method signature="TC02_GetWeatherDetailsForInvalidCity()[pri:0, instance:GET_Request.Request_Data@229d10bd]" started-at="2020-07-28T14:23:06 EEST" name="TC02_GetWeatherDetailsForInvalidCity" finished-at="2020-07-28T14:23:07 EEST" duration-ms="537" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Correct status code returned expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Correct status code returned expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Assertion.Assertions_types.checkStatusIs200(Assertions_types.java:11)
at GET_Request.Request_Data.TC02_GetWeatherDetailsForInvalidCity(Request_Data.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetWeatherDetailsForInvalidCity -->
        <test-method signature="TC03_GetWeatherDetailsForEmptyCity()[pri:0, instance:GET_Request.Request_Data@229d10bd]" started-at="2020-07-28T14:23:07 EEST" name="TC03_GetWeatherDetailsForEmptyCity" finished-at="2020-07-28T14:23:07 EEST" duration-ms="345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_GetWeatherDetailsForEmptyCity -->
      </class> <!-- GET_Request.Request_Data -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
